/* Generated by LP Compiler */
#define LP_MAIN_FILE
#include "lp_runtime.h"
#include "lp_native_modules.h"
#include "lp_http.h"
#include "lp_json.h"
#include "lp_sqlite.h"
#include "lp_thread.h"

__attribute__((hot, optimize("O3,unroll-loops,strict-aliasing,omit-frame-pointer"))) int64_t lp_fetch_worker(const char* lp_url) {
    const char* lp_data = lp_http_get(lp_url);
    sqlite3* lp_db = lp_sqlite_connect("analytics.db");
    lp_sqlite_execute(lp_db, "CREATE TABLE IF NOT EXISTS server (responses TEXT);");
    lp_sqlite_execute(lp_db, lp_str_concat(lp_str_concat("INSERT INTO server (responses) VALUES ('", lp_url), "');"));
    return 1;
}

__attribute__((hot, optimize("O3,unroll-loops,strict-aliasing,omit-frame-pointer"))) int64_t lp_main() {
    lp_print_str("Initiating Multi-Thread Web Server Scrape!");
    const char* lp_link1 = "https://jsonplaceholder.typicode.com/posts/1";
    const char* lp_link2 = "https://jsonplaceholder.typicode.com/posts/2";
    LpThread lp_t1 = lp_thread_spawn((void* (*)(void*))lp_fetch_worker, lp_link1);
    LpThread lp_t2 = lp_thread_spawn((void* (*)(void*))lp_fetch_worker, lp_link2);
    lp_thread_join(lp_t1);
    lp_thread_join(lp_t2);
    lp_print_str("Finished downloads!");
}

int main(void) {
    lp_main();
    return 0;
}
