/* Generated by LP Compiler */
#define LP_MAIN_FILE
#include "lp_runtime.h"
#include "lp_native_modules.h"
#include "lp_memory.h"

typedef struct {
    double lp_velocity;
    int64_t lp_life;
} LpObj_Particle;

static inline void Particle_init(LpObj_Particle* self) {
    self->lp_velocity = 0;
    self->lp_life = 10;
}

__attribute__((hot, optimize("O3,unroll-loops,strict-aliasing,omit-frame-pointer"))) double lp_simulate_particle(void* lp_p_ptr) {
    LpObj_Particle* lp_p = lp_memory_cast(lp_p_ptr, lp_Particle);
    lp_p->lp_life = (lp_p->lp_life - 1);
    lp_p->lp_velocity = (lp_p->lp_velocity * 1.5);
    return lp_p->lp_velocity;
}

__attribute__((hot, optimize("O3,unroll-loops,strict-aliasing,omit-frame-pointer"))) int64_t lp_main() {
    lp_print_str("Instantiating memory Arena!");
    void* lp_arena = lp_memory_arena_new(102400);
    void* lp_p1 = lp_memory_arena_alloc(lp_arena, 16);
    lp_memory_arena_free(lp_arena);
    lp_print_str("Wiped Arena buffers without GC latency!");
}

int main(void) {
    lp_main();
    return 0;
}
