/* Generated by LP Compiler */
#define LP_MAIN_FILE
#include "lp_runtime.h"
#include "lp_native_modules.h"
#include "lp_sqlite.h"
#include "lp_platform.h"

__attribute__((hot, optimize("O3,unroll-loops,strict-aliasing,omit-frame-pointer"))) int64_t lp_main() {
    LpVal lp_os = lp_platform_os();
    int64_t lp_cores = lp_platform_cores();
    LpVal lp_arch = lp_platform_arch();
    lp_print_str("--- SYSTEM DIAGNOSTIC ---");
    lp_print_generic(lp_os);
    lp_print_generic(lp_arch);
    lp_print_str("Initializing Database...");
    sqlite3* lp_db = lp_sqlite_connect("system.db");
    lp_sqlite_execute(lp_db, "CREATE TABLE IF NOT EXISTS sys_logs (os TEXT, cores INTEGER);");
    lp_sqlite_execute(lp_db, "INSERT INTO sys_logs (os, cores) VALUES ('windows', 8);");
    LpVal lp_rows = lp_sqlite_query(lp_db, "SELECT * FROM sys_logs");
    lp_print_str("Database persisted entries correctly.");
}

int main(void) {
    lp_main();
    return 0;
}
