# Generated by LP Compiler (Assembly Backend)
# Target: x86-64 (System V AMD64 ABI)

    .text

    .globl main
main:
    pushq %rbp
    movq %rsp, %rbp
    subq $256, %rsp
    pushq %rbx
    pushq %r12
    pushq %r13
    pushq %r14
    pushq %r15
    movq $7, %rax
    movq %rax, -8(%rbp)
    movq -8(%rbp), %rax
    jmp .Lepilogue
.Lepilogue:
    popq %r15
    popq %r14
    popq %r13
    popq %r12
    popq %rbx
    movq %rbp, %rsp
    popq %rbp
    ret

    .globl _start
_start:
    call main
    movq %rax, %rdi
    movq $60, %rax
    syscall
