sed -i 's/TOK_PERCENT,/TOK_PERCENT,\n    TOK_BIT_AND, TOK_BIT_OR, TOK_BIT_XOR, TOK_BIT_NOT,\n    TOK_LSHIFT, TOK_RSHIFT,/' compiler/src/lexer.h
sed -i 's/TOK_SLASH_ASSIGN,/TOK_SLASH_ASSIGN,\n    TOK_BIT_AND_ASSIGN, TOK_BIT_OR_ASSIGN, TOK_BIT_XOR_ASSIGN,\n    TOK_LSHIFT_ASSIGN, TOK_RSHIFT_ASSIGN,/' compiler/src/lexer.h
