/* Generated by LP Compiler */
#define LP_MAIN_FILE
#include "lp_runtime.h"

typedef struct {
    double lp_x;
    double lp_y;
} LpObj_Entity;

static inline void Entity_init(LpObj_Entity* self) {
    self->lp_x = 0;
    self->lp_y = 0;
}

typedef struct {
    double lp_x;
    double lp_y;
    int64_t lp_health;
    const char* lp_name;
} LpObj_Player;

static inline void Player_init(LpObj_Player* self) {
    Entity_init((LpObj_Entity*)self);
    self->lp_health = 100;
    self->lp_name = "Hero";
}

typedef struct {
    double lp_x;
    double lp_y;
    int64_t lp_damage;
} LpObj_Enemy;

static inline void Enemy_init(LpObj_Enemy* self) {
    Entity_init((LpObj_Entity*)self);
    self->lp_damage = 15;
}

__attribute__((hot, optimize("O3,unroll-loops,strict-aliasing,omit-frame-pointer"))) double lp_Entity_move(LpObj_Entity* lp_self, double lp_dx, double lp_dy) {
    lp_self->lp_x = (lp_self->lp_x + lp_dx);
    lp_self->lp_y = (lp_self->lp_y + lp_dy);
    return lp_self->lp_x;
}

__attribute__((hot, optimize("O3,unroll-loops,strict-aliasing,omit-frame-pointer"))) int64_t lp_Player_take_damage(LpObj_Player* lp_self, int64_t lp_amount) {
    lp_self->lp_health = (lp_self->lp_health - lp_amount);
    return lp_self->lp_health;
}

__attribute__((hot, optimize("O3,unroll-loops,strict-aliasing,omit-frame-pointer"))) const char* lp_Player_profile(LpObj_Player* lp_self) {
    return lp_self->lp_name;
}

__attribute__((hot, optimize("O3,unroll-loops,strict-aliasing,omit-frame-pointer"))) int64_t lp_Enemy_attack(LpObj_Enemy* lp_self, LpObj_Player* lp_target) {
    return lp_Player_take_damage((LpObj_Player*)lp_target, lp_self->lp_damage);
}

__attribute__((hot, optimize("O3,unroll-loops,strict-aliasing,omit-frame-pointer"))) int64_t lp_main() {
    LpObj_Player* lp_p = ({ LpObj_Player* _lp_tmp_obj = (LpObj_Player*)malloc(sizeof(LpObj_Player)); Player_init(_lp_tmp_obj); _lp_tmp_obj; });
    lp_p->lp_name = "Arthur";
    LpObj_Enemy* lp_e = ({ LpObj_Enemy* _lp_tmp_obj = (LpObj_Enemy*)malloc(sizeof(LpObj_Enemy)); Enemy_init(_lp_tmp_obj); _lp_tmp_obj; });
    lp_e->lp_damage = 25;
    lp_Entity_move((LpObj_Entity*)lp_e, 10.5, 5);
    lp_Entity_move((LpObj_Entity*)lp_p, 10.5, 5);
    lp_print_str("Player Health initially:");
    lp_print_generic(lp_p->lp_health);
    lp_print_str("Enemy Attacks!");
    lp_Enemy_attack((LpObj_Enemy*)lp_e, lp_p);
    lp_print_str("Player Health after:");
    lp_print_generic(lp_p->lp_health);
}

int main(void) {
    lp_main();
    return 0;
}
